export const mentees = [ 
    { 
 // Ideal match with Mentor 1 
    id: 1,  
    name: "Mentee 1", 
    skills: ["JavaScript", "Python"],
    experience: 0, 
    age: 26, 
    location: "City X", 
    }, 
    { 
    // Great match with Mentor 1, but negative that mentee is older than mentor 
    id: 2, 
    name: "Mentee 2", 
    skills: ["Python", "Java", "JavaScript"], 
    location: "City X", 
    age: 31, 
    experience: 1, 
    }, 
    { 
    id: 3, 
    name: "Mentee 3", 
    skills: ["Java", "C++"], 
    location: "City Z", 
    age: 30, 
    experience: 0, 
    },
    {
    id: 4,
    name: "Mentee 4",
    skills: ["JavaScript", "C++"],
    experience: 2,
    age: 28,
    location: "City Y",
    },
    {
    id: 5,
    name: "Mentee 5",
    skills: ["Java", "Python"],
    experience: 0,
    age: 23,
    location: "City Z",
    },
      
]; 
    
 // Sample Data for Mentors 
export const mentors = [ 
    { 
    id: 1, 
    skills: ["JavaScript", "Python", "C++"], 
    experience: 6, 
    age: 30, 
    location: "City X", 
    name: "Mentor 1", 
    },  
    { 
    id: 2, 
    skills: ["Python", "Java", "JavaScript"], 
    experience: 7, 
    age: 31, 
    location: "City B", 
    name: "Mentor 2", 
    }, 
    { 
    id: 3, 
    skills: ["Java", "C++"], 
    experience: 8, 
    age: 32, 
    location: "City C", 
    name: "Mentor 3", 
    }, 
    { 
    id: 4, 
    skills: ["C++", "JavaScript"], 
    experience: 9, 
    age: 33, 
    location: "City A", 
    name: "Mentor 4", 
    }, 
    { 
    id: 5, 
    skills: ["Python", "Java"], 
    experience: 6, 
    age: 34, 
    location: "City B", 
    name: "Mentor 5", 
    },
    {
    id: 6,
    skills: ["JavaScript", "Python", "C++"],
    experience: 6,
    age: 30,
    location: "City X",
    name: "Mentor 6",
    },
    {
    id: 7,
    skills: ["Python", "Java", "JavaScript"],
    experience: 7,
    age: 31,
    location: "City B",
    name: "Mentor 7",
    },
    {
    id: 8,
    skills: ["Java", "C++"],
    experience: 4,
    age: 28,
    location: "City B",
    name: "Mentor 8",
    },
    {
    id: 9,
    skills: ["Python", "Ruby"],
    experience: 2,
    age: 24,
    location: "City X",
    name: "Mentor 9",
    },
    {
    id: 10,
    skills: ["JavaScript", "C++"],
    experience: 5,
    age: 29,
    location: "City Y",
    name: "Mentor 10",
    },
    {
    id: 11,
    skills: ["Java", "Python", "C++"],
    experience: 8,
    age: 32,
    location: "City Z",
    name: "Mentor 11",
    },
    {
    id: 12,
    skills: ["Java", "C++"],
    experience: 6,
    age: 30,
    location: "City B",
    name: "Mentor 12",
    },
    {
    id: 13,
    skills: ["JavaScript", "Python"],
    experience: 9,
    age: 35,
    location: "City X",
    name: "Mentor 13",
    },
    {
    id: 14,
    skills: ["Python", "Java"],
    experience: 3,
    age: 27,
    location: "City Y",
    name: "Mentor 14",
    },
    {
    id: 15,
    skills: ["Python", "Ruby", "C++"],
    experience: 7,
    age: 31,
    location: "City Z",
    name: "Mentor 15",
    },
]; 

// Sample data for mentees batching
export const menteesBatch = [
    {
      id: 1,
      name: "Mentee 1",
      skills: ["JavaScript", "Python"],
      experience: 0,
      age: 26,
      location: "City X",
    },
    {
      id: 2,
      name: "Mentee 2",
      skills: ["Java", "C++"],
      experience: 3,
      age: 24,
      location: "City B",
    },
    {
      id: 3,
      name: "Mentee 3",
      skills: ["Python", "Ruby"],
      experience: 1,
      age: 29,
      location: "City X",
    },
    {
      id: 4,
      name: "Mentee 4",
      skills: ["JavaScript", "C++"],
      experience: 2,
      age: 28,
      location: "City Y",
    },
    {
      id: 5,
      name: "Mentee 5",
      skills: ["Java", "Python"],
      experience: 0,
      age: 23,
      location: "City Z",
    },
    {
      id: 6,
      name: "Mentee 6",
      skills: ["Python", "C++"],
      experience: 1,
      age: 27,
      location: "City X",
    },
    {
      id: 7,
      name: "Mentee 7",
      skills: ["JavaScript", "Java"],
      experience: 2,
      age: 25,
      location: "City Y",
    },
    {
      id: 8,
      name: "Mentee 8",
      skills: ["C++", "Ruby"],
      experience: 0,
      age: 22,
      location: "City Z",
    },
    {
      id: 9,
      name: "Mentee 9",
      skills: ["Java", "Python"],
      experience: 4,
      age: 30,
      location: "City X",
    },
    {
      id: 10,
      name: "Mentee 10",
      skills: ["JavaScript", "C++"],
      experience: 3,
      age: 26,
      location: "City B",
    },
  ];


  // Sample data for mentors batching
  export const mentorsBatch = [
    {
      id: 1,
      skills: ["JavaScript", "Python", "C++"],
      experience: 6,
      age: 30,
      location: "City X",
      name: "Mentor 1",
    },
    {
      id: 2,
      skills: ["Python", "Java", "JavaScript"],
      experience: 7,
      age: 31,
      location: "City B",
      name: "Mentor 2",
    },
    {
      id: 3,
      skills: ["Java", "C++"],
      experience: 4,
      age: 28,
      location: "City B",
      name: "Mentor 3",
    },
    {
      id: 4,
      skills: ["Python", "Ruby"],
      experience: 2,
      age: 24,
      location: "City X",
      name: "Mentor 4",
    },
    {
      id: 5,
      skills: ["JavaScript", "C++"],
      experience: 5,
      age: 29,
      location: "City Y",
      name: "Mentor 5",
    },
    {
      id: 6,
      skills: ["Java", "Python", "C++"],
      experience: 8,
      age: 32,
      location: "City Z",
      name: "Mentor 6",
    },
    {
      id: 7,
      skills: ["Java", "C++"],
      experience: 6,
      age: 30,
      location: "City B",
      name: "Mentor 7",
    },
    {
      id: 8,
      skills: ["JavaScript", "Python"],
      experience: 9,
      age: 35,
      location: "City X",
      name: "Mentor 8",
    },
    {
      id: 9,
      skills: ["Python", "Java"],
      experience: 3,
      age: 27,
      location: "City Y",
      name: "Mentor 9",
    },
    {
      id: 10,
      skills: ["Python", "Ruby", "C++"],
      experience: 7,
      age: 31,
      location: "City Z",
      name: "Mentor 10",
    },
    {
      id: 11,
      skills: ["Python", "Data Science"],
      experience: 4,
      age: 29,
      location: "City Y",
      name: "Mentor 11",
    },
    {
      id: 12,
      skills: ["JavaScript", "React", "Node.js"],
      experience: 5,
      age: 27,
      location: "City X",
      name: "Mentor 12",
    },
    {
      id: 13,
      skills: ["C++", "Unity", "Game Development"],
      experience: 6,
      age: 31,
      location: "City Z",
      name: "Mentor 13",
    },
    {
      id: 14,
      skills: ["Python", "Machine Learning"],
      experience: 3,
      age: 25,
      location: "City B",
      name: "Mentor 14",
    },
    {
      id: 15,
      skills: ["Java", "Spring Boot", "Microservices"],
      experience: 8,
      age: 34,
      location: "City X",
      name: "Mentor 15",
    },
    {
      id: 16,
      skills: ["JavaScript", "Angular", "TypeScript"],
      experience: 7,
      age: 32,
      location: "City Y",
      name: "Mentor 16",
    },
    {
      id: 17,
      skills: ["Python", "Web Development"],
      experience: 5,
      age: 28,
      location: "City Z",
      name: "Mentor 17",
    },
    {
      id: 18,
      skills: ["C#", ".NET Core", "Azure"],
      experience: 6,
      age: 29,
      location: "City B",
      name: "Mentor 18",
    },
    {
      id: 19,
      skills: ["Java", "Spring Framework", "Hibernate"],
      experience: 9,
      age: 35,
      location: "City X",
      name: "Mentor 19",
    },
    {
      id: 20,
      skills: ["JavaScript", "Vue.js", "Firebase"],
      experience: 4,
      age: 26,
      location: "City Y",
      name: "Mentor 20",
    },
  ];